#pragma once

// Auto-generated by CMake -- do not edit
#define REXGLUE_VERSION_MAJOR 0
#define REXGLUE_VERSION_MINOR 8
#define REXGLUE_VERSION_PATCH 1
#define REXGLUE_VERSION_TWEAK 32
#define REXGLUE_VERSION_STRING "0.8.1.32-dev.gf22cd9d"
#define REXGLUE_VERSION_NUMERIC "0.8.1.32"
#define REXGLUE_VERSION_FLOOR "0.8.1"

#define REXGLUE_BUILD_PLATFORM "win-amd64"
#define REXGLUE_BUILD_TIMESTAMP "20260605_0940"

// Requires REXGLUE_BUILD_CONFIG compile definition
// Title: "[rexglue-v0.7.5.38-dev.gb27f3f74-Release]"
#define REXGLUE_BUILD_TITLE \
  "[rexglue-v" REXGLUE_VERSION_STRING "-" REXGLUE_BUILD_CONFIG "]"

// Overlay: "build: rexglue-v0.7.5.38-dev.gb27f3f74-win-amd64-Release@20260420_1430"
#define REXGLUE_BUILD_STAMP \
  "build: rexglue-v" REXGLUE_VERSION_STRING "-" REXGLUE_BUILD_PLATFORM \
  "-" REXGLUE_BUILD_CONFIG "@" REXGLUE_BUILD_TIMESTAMP
