// file_to_c - Converts binary files to C arrays for embedding
// Adapted for SanRecomp build system

#include <filesystem>
#include <fstream>
#include <cstdio>
#include <vector>
#include <string_view>

std::vector<char> read_file(const char* path) {
    std::ifstream input_file{path, std::ios::binary};
    std::vector<char> ret{};
    if (!input_file.good()) return ret;
    input_file.seekg(0, std::ios::end);
    ret.resize(input_file.tellg());
    input_file.seekg(0, std::ios::beg);
    input_file.read(ret.data(), ret.size());
    return ret;
}

void create_parent_if_needed(const char* path) {
    std::filesystem::path parent_path = std::filesystem::path{path}.parent_path();
    if (!parent_path.empty()) std::filesystem::create_directories(parent_path);
}

int main(int argc, const char** argv) {
    if (argc < 6) {
        printf("Usage: %s [input file] [array name] [compression] [output C] [output H]\n", argv[0]);
        printf("  compression: 'none' or 'zstd' (zstd not yet implemented, treated as none)\n");
        return 1;
    }

    const char* input_path = argv[1];
    const char* array_name = argv[2];
    const char* output_c_path = argv[4];
    const char* output_h_path = argv[5];

    std::vector<char> contents = read_file(input_path);
    if (contents.empty()) {
        fprintf(stderr, "Failed to open file '%s' or it's empty, generating placeholder.\n", input_path);
        contents.push_back(0);
    }

    create_parent_if_needed(output_c_path);
    create_parent_if_needed(output_h_path);

    // Write C file
    {
        std::ofstream out{output_c_path};
        out << "// Auto-generated by file_to_c\n\n";
        out << "#include <stddef.h>\n\n";
        out << "const unsigned char " << array_name << "[" << contents.size() << "] = {";
        for (size_t i = 0; i < contents.size(); ++i) {
            if (i % 16 == 0) out << "\n    ";
            out << (int)(unsigned char)contents[i] << ",";
        }
        out << "\n};\n\n";
        out << "const size_t " << array_name << "_size = " << contents.size() << ";\n";
    }

    // Write header
    {
        std::ofstream out{output_h_path};
        out << "// Auto-generated by file_to_c\n\n#pragma once\n\n#include <stddef.h>\n\n";
        out << "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n";
        out << "extern const unsigned char " << array_name << "[" << contents.size() << "];\n";
        out << "extern const size_t " << array_name << "_size;\n\n";
        out << "#ifdef __cplusplus\n}\n#endif\n";
    }

    return 0;
}
